shell zsh

font_family      JetBrains Mono
font_size 14.5

cursor #ad8ee6
cursor_shape block

#: The cursor shape can be one of block, beam, underline. Note that
cursor_beam_thickness 1.5
background_opacity 0.95
window_padding_width 8

[blur]
background=true

# --- Esquema Neutro Oscurecido ---

# Fondo: Un gris cálido neutro, nada de tonos amarillentos/beige
background            #3d3b39
# Texto: Un blanco hueso muy suave para no cansar la vista
foreground            #d5d2cc

# Selección: Un gris un poco más claro para resaltar
selection_background  #575451
selection_foreground  #d5d2cc

# --- Cursor (Blanco y Gordo) ---
cursor                #ffffff
cursor_text_color     #3d3b39
cursor_shape          block

# --- Colores ANSI (Ajustados para este fondo) ---

# Negro
color0  #242424
color8  #575451

# Rojo (Tierra apagado)
color1  #b46958
color9  #cf7c69

# Verde (El verde de tu nvim, ahora más neutro)
color2  #8a9a7b
color10 #a3b091

# Amarillo / Ocre (Bronce neutro)
color3  #a89371
color11 #c3b194

# Azul / Grisáceo
color4  #7d8fa3
color12 #98a9ba

# Blanco
color7  #d5d2cc
color15 #ffffff

# 1. Quita la barra pero mantiene la compatibilidad con el sistema
hide_window_decorations titlebar-only

# 2. Obliga a que no haya bordes de colores raros
window_border_width 0
draw_minimal_borders yes

# 3. Evita que GNOME intente dibujar sombras donde no debe
linux_display_server x11

